#!/usr/bin/env python3
"""
Complete seoContent translations for all 60 tools
Hindi and Portuguese-Brazil
"""
import json
from pathlib import Path

# ============ COMPLETE TRANSLATION DICTIONARIES ============

HINDI_TRANSLATIONS = {
    "json-formatter": {
        "intro": {"title": "JSON Formatter क्या है?", "content": "<p><strong>JSON Formatter</strong> JSON डेटा को फॉर्मेट, सत्यापित और minify करने के लिए एक मुफ्त ब्राउज़र टूल है।</p><p>API प्रतिक्रियाओं को debug करने, कॉन्फ़िगरेशन फाइलों की समीक्षा करने, या डॉक्यूमेंटेशन के लिए डेटा तैयार करते समय यह टूल JSON को आसान बनाता है।</p>"},
        "howToUse": {"title": "JSON Formatter का उपयोग कैसे करें", "content": "<ol><li>Input area में JSON डेटा पेस्ट करें</li><li>अपना पसंदीदा indentation स्तर चुनें (2 या 4 spaces)</li><li><strong>Format</strong>, <strong>Minify</strong>, या <strong>Validate</strong> क्लिक करें</li><li>परिणाम को कॉपी करें या डाउनलोड करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Pretty Print</strong>: JSON को फॉर्मेट करें</li><li><strong>Minify</strong>: JSON को compress करें</li><li><strong>Validate</strong>: Syntax जांचें</li><li><strong>Syntax Highlighting</strong>: Color-coded output</li><li><strong>Large Data Support</strong>: बड़ी files handle करें</li><li><strong>100% Browser-Based</strong>: कोई uploads नहीं</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>API Development</strong>: Responses को फॉर्मेट करें</li><li><strong>Configuration Files</strong>: Config files को साफ़ करें</li><li><strong>Data Validation</strong>: JSON verify करें</li><li><strong>Documentation</strong>: Examples तैयार करें</li><li><strong>Database Records</strong>: NoSQL data को format करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम JSON Processing", "content": "<p>डेटा <strong>पूरी तरह ब्राउज़र में</strong> processed होता है।</p><ul><li>डेटा <strong>कभी device को नहीं छोड़ता</strong></li><li>API keys के लिए safe</li><li><strong>Offline काम करता है</strong></li><li>Zero upload requests</li></ul>"}
    },
    "base64": {
        "intro": {"title": "Base64 एन्कोडर/डिकोडर क्या है?", "content": "<p><strong>Base64 एन्कोडर/डिकोडर</strong> text को Base64 में convert करता है।</p><p>किसी भी text को तुरंत encode या decode करें।</p>"},
        "howToUse": {"title": "Base64 का उपयोग कैसे करें", "content": "<ol><li>Text enter करें</li><li><strong>Encode</strong> या <strong>Decode</strong> चुनें</li><li>Result तुरंत दिखाई देता है</li><li>Copy करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Instant Encoding</strong>: Real-time conversion</li><li><strong>Instant Decoding</strong>: Decode करें</li><li><strong>UTF-8 Support</strong>: Unicode handle करता है</li><li><strong>Error Detection</strong>: Invalid input alert करता है</li><li><strong>One-Click Copy</strong>: Instantly copy करें</li><li><strong>No Size Limits</strong>: कोई limit नहीं</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>Data URIs</strong>: Images को encode करें</li><li><strong>API Authentication</strong>: Credentials encode करें</li><li><strong>Email Attachments</strong>: MIME data encode/decode करें</li><li><strong>JWT Tokens</strong>: Tokens decode करें</li><li><strong>Configuration</strong>: Config में data encode करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Base64 Processing", "content": "<p>Encoding और decoding <strong>ब्राउज़र में</strong> होता है।</p><ul><li>Text <strong>कभी device को नहीं छोड़ता</strong></li><li>Sensitive credentials के लिए ideal</li><li>कोई server processing नहीं</li><li>Offline काम करता है</li></ul>"}
    },
    "url-encoder": {
        "intro": {"title": "URL एन्कोडर/डिकोडर क्या है?", "content": "<p><strong>URL एन्कोडर/डिकोडर</strong> URLs में special characters को encode/decode करता है।</p><p>Query parameters को safely pass करने या malformed URLs को debug करने के लिए उपयोग करें।</p>"},
        "howToUse": {"title": "URL एन्कोडर/डिकोडर का उपयोग कैसे करें", "content": "<ol><li>URL या text enter करें</li><li><strong>Encode</strong> या <strong>Decode</strong> चुनें</li><li>Result instantly दिखाई देता है</li><li>Copy करें</li></ol><p>RFC 3986 compliant encoding।</p>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>RFC 3986 Compliant</strong>: सभी unsafe characters को encode करता है</li><li><strong>Real-Time Processing</strong>: तुरंत results</li><li><strong>Unicode Support</strong>: International characters handle करता है</li><li><strong>Component Encoding</strong>: URL components को encode करें</li><li><strong>One-Click Copy</strong>: Instantly copy</li><li><strong>100% Browser-Based</strong>: कोई uploads नहीं</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>Query Parameters</strong>: Parameters को safely encode करें</li><li><strong>API Requests</strong>: REST APIs के लिए parameters encode करें</li><li><strong>Redirect URLs</strong>: OAuth callback URLs encode करें</li><li><strong>File Paths</strong>: File names को encode करें</li><li><strong>Debugging</strong>: URLs को decode करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम URL Processing", "content": "<p>Encoding और decoding <strong>ब्राउज़र में</strong> होता है।</p><ul><li>URLs <strong>कभी device को नहीं छोड़ते</strong></li><li>API keys को safely encode करें</li><li>Offline काम करता है</li></ul>"}
    },
    "ocr": {
        "intro": {"title": "OCR Text Recognition क्या है?", "content": "<p><strong>OCR Text Recognition</strong> images से text को extract करता है।</p><p>12+ languages को support करता है जिसमें English, Chinese, Japanese शामिल हैं।</p>"},
        "howToUse": {"title": "OCR का उपयोग कैसे करें", "content": "<ol><li>Image upload करें (JPG, PNG, WebP, BMP)</li><li>Image में text की language चुनें</li><li><strong>Extract Text</strong> क्लिक करें</li><li>Extracted text को copy करें</li></ol><p>Best results के लिए clear, high-contrast images उपयोग करें।</p>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>12+ Languages</strong>: 12+ languages support करता है</li><li><strong>Multiple Image Formats</strong>: JPG, PNG, WebP, BMP, TIFF accept करता है</li><li><strong>Powered by Tesseract.js</strong>: Industry-standard engine</li><li><strong>High Accuracy</strong>: Printed text के लिए best results</li><li><strong>Copy & Edit</strong>: Extracted text को edit करें</li><li><strong>100% Local Processing</strong>: कोई uploads नहीं</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>Document Digitization</strong>: Documents को text में convert करें</li><li><strong>Screenshot Text Extraction</strong>: Screenshots से text निकालें</li><li><strong>Translation Prep</strong>: Foreign language text निकालें</li><li><strong>Data Entry</strong>: Forms से data digitize करें</li><li><strong>Accessibility</strong>: Image text को accessible बनाएं</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम OCR Processing", "content": "<p>OCR <strong>ब्राउज़र में</strong> Tesseract.js के साथ चलता है।</p><ul><li>Images <strong>कभी device को नहीं छोड़ते</strong></li><li>Sensitive documents के लिए critical</li><li>कोई cloud API calls नहीं</li><li>Language models को locally cache किया जाता है</li></ul>"}
    },
    "archive": {
        "intro": {"title": "ZIP Extractor क्या है?", "content": "<p><strong>ZIP Extractor</strong> ZIP archives को open और extract करता है।</p><p>किसी भी software installation के बिना browse करें।</p>"},
        "howToUse": {"title": "ZIP Extractor का उपयोग कैसे करें", "content": "<ol><li>ZIP file को page पर drop करें</li><li>Archive contents को देखें</li><li>Individual files को download करें या सब extract करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Instant Preview</strong>: Extract किए बिना contents देखें</li><li><strong>Selective Extraction</strong>: Individual files download करें</li><li><strong>File Size Display</strong>: Compressed और uncompressed sizes दिखाता है</li><li><strong>Folder Structure</strong>: Directory hierarchy browse करें</li><li><strong>Powered by fflate</strong>: High-performance decompression</li><li><strong>No File Size Limits</strong>: Device memory तक कोई limit नहीं</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>Quick File Inspection</strong>: ZIP को check करें</li><li><strong>Single File Download</strong>: सिर्फ जरूरी file लें</li><li><strong>Mobile Use</strong>: Phones पर ZIP files open करें</li><li><strong>Chromebook Users</strong>: Native tools नहीं होने पर use करें</li><li><strong>Email Attachments</strong>: ZIP attachments देखें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Archive Extraction", "content": "<p>Extraction <strong>ब्राउज़र में</strong> fflate के साथ होता है।</p><ul><li>Archives <strong>कभी device को नहीं छोड़ते</strong></li><li>Confidential documents के लिए safe</li><li>कोई server-side processing नहीं</li><li>Offline काम करता है</li></ul>"}
    },
    "csv-json": {
        "intro": {"title": "CSV/JSON Converter क्या है?", "content": "<p><strong>CSV/JSON Converter</strong> CSV और JSON के बीच data को transform करता है।</p><p>Spreadsheet data को JSON में या JSON को Excel/Sheets में convert करें।</p>"},
        "howToUse": {"title": "CSV/JSON Converter का उपयोग कैसे करें", "content": "<ol><li>CSV या JSON data paste करें</li><li>Conversion direction चुनें</li><li>Result instantly दिखाई देता है</li><li>Copy करें या download करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Bidirectional Conversion</strong>: दोनों directions में convert करें</li><li><strong>Auto Header Detection</strong>: CSV की first row को keys के रूप में उपयोग करता है</li><li><strong>Handles Special Characters</strong>: Quoted fields, commas handle करता है</li><li><strong>Instant Conversion</strong>: तुरंत results</li><li><strong>Download Output</strong>: .json या .csv download करें</li><li><strong>Large Dataset Support</strong>: हजारों rows efficiently handle करता है</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>API Integration</strong>: Spreadsheet को JSON में convert करें</li><li><strong>Data Analysis</strong>: JSON responses को CSV में convert करें</li><li><strong>Database Migration</strong>: Data formats को convert करें</li><li><strong>Reporting</strong>: JSON logs को CSV में convert करें</li><li><strong>Prototyping</strong>: Sample JSON data बनाएं</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Data Conversion", "content": "<p>Conversion <strong>ब्राउज़र में</strong> JavaScript से होता है।</p><ul><li>Data <strong>कभी device को नहीं छोड़ता</strong></li><li>Business data के लिए safe</li><li>कोई server processing नहीं</li><li>Offline काम करता है</li></ul>"}
    },
    "hash-generator": {
        "intro": {"title": "Hash Generator क्या है?", "content": "<p><strong>Hash Generator</strong> SHA-1, SHA-256, SHA-384, SHA-512 hashes compute करता है।</p><p>Data integrity verify करने के लिए hashes generate करें।</p>"},
        "howToUse": {"title": "Hash Generator का उपयोग कैसे करें", "content": "<ol><li>Text enter करें या file upload करें</li><li>Hash algorithm(s) चुनें</li><li>Hash value instantly compute होता है</li><li>Copy करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Multiple Algorithms</strong>: SHA-1, SHA-256, SHA-384, SHA-512</li><li><strong>Text & File Hashing</strong>: Text या files को hash करें</li><li><strong>Instant Computation</strong>: Real-time results</li><li><strong>Web Crypto API</strong>: Browser के native engine का उपयोग</li><li><strong>Copy to Clipboard</strong>: One-click copy</li><li><strong>Large File Support</strong>: किसी भी size की files</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>File Integrity</strong>: Downloaded files verify करें</li><li><strong>Content Deduplication</strong>: Duplicate files find करें</li><li><strong>Digital Signatures</strong>: Content digests बनाएं</li><li><strong>Software Distribution</strong>: Checksums generate करें</li><li><strong>Security Auditing</strong>: Unauthorized changes detect करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Hash Generation", "content": "<p>Hashes <strong>ब्राउज़र में</strong> Web Crypto API से compute होते हैं।</p><ul><li>Text और files <strong>कभी device को नहीं छोड़ते</strong></li><li>Sensitive content को hash करने के लिए critical</li><li>Hardware acceleration उपयोग करता है</li><li>Offline काम करता है</li></ul>"}
    },
    "color-converter": {
        "intro": {"title": "Color Converter क्या है?", "content": "<p><strong>Color Converter</strong> colors को HEX, RGB, HSL के बीच convert करता है।</p><p>Live visual preview के साथ colors को convert करें।</p>"},
        "howToUse": {"title": "Color Converter का उपयोग कैसे करें", "content": "<ol><li>Color value enter करें (HEX, RGB, या HSL)</li><li>सभी formats में instant conversion दिखाई देता है</li><li>Copy करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Three Format Support</strong>: HEX, RGB, HSL</li><li><strong>Live Preview</strong>: Actual color दिखाता है</li><li><strong>Visual Color Picker</strong>: Colors को visually select करें</li><li><strong>Instant Conversion</strong>: Real-time results</li><li><strong>One-Click Copy</strong>: Copy करें</li><li><strong>CSS-Ready Output</strong>: Direct CSS use के लिए formatted</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>CSS Development</strong>: Color formats convert करें</li><li><strong>Design Handoff</strong>: Design colors को code values में convert करें</li><li><strong>Brand Guidelines</strong>: Brand colors को formats में convert करें</li><li><strong>Accessibility</strong>: Contrast requirements के लिए adjust करें</li><li><strong>Theme Development</strong>: Color variables बनाएं</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Color Processing", "content": "<p>Conversion <strong>ब्राउज़र में</strong> pure JavaScript से होता है।</p><ul><li>कोई data transmitted नहीं</li><li>Colors पूरी तरह device पर रहते हैं</li><li>Offline काम करता है</li></ul>"}
    },
    "json-xml": {
        "intro": {"title": "JSON ↔ XML Converter क्या है?", "content": "<p><strong>JSON ↔ XML Converter</strong> JSON और XML के बीच data को transform करता है।</p><p>Different data formats का उपयोग करने वाले systems को integrate करें।</p>"},
        "howToUse": {"title": "JSON ↔ XML Converter का उपयोग कैसे करें", "content": "<ol><li>JSON या XML data paste करें</li><li>Conversion direction चुनें</li><li>Output instantly दिखाई देता है</li><li>Copy या download करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Bidirectional Conversion</strong>: दोनों directions में convert करें</li><li><strong>Nested Structure Support</strong>: Deeply nested objects और arrays को handle करता है</li><li><strong>Pretty-Printed Output</strong>: Properly indented output</li><li><strong>Array Handling</strong>: JSON arrays को repeated XML elements में convert करता है</li><li><strong>Instant Processing</strong>: तुरंत results</li><li><strong>Download Output</strong>: .json या .xml download करें</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>API Integration</strong>: JSON REST APIs और XML SOAP services के बीच convert करें</li><li><strong>Legacy Systems</strong>: Old systems के XML को modern JSON में convert करें</li><li><strong>Configuration</strong>: Configuration file formats के बीच convert करें</li><li><strong>Data Migration</strong>: System migrations के दौरान convert करें</li><li><strong>Testing</strong>: XML या JSON test data generate करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Data Conversion", "content": "<p>Conversion <strong>ब्राउज़र में</strong> JavaScript XML parsing से होता है।</p><ul><li>Data <strong>कभी device को नहीं छोड़ता</strong></li><li>Business data के लिए safe</li><li>Configuration files के लिए safe</li><li>Offline काम करता है</li></ul>"}
    },
    "markdown-preview": {
        "intro": {"title": "Markdown Preview क्या है?", "content": "<p><strong>Markdown Preview</strong> आपको Markdown लिखने और live HTML preview देखने देता है।</p><p>Simple Markdown syntax के साथ formatted text लिखें।</p>"},
        "howToUse": {"title": "Markdown Preview का उपयोग कैसे करें", "content": "<ol><li>Left pane में Markdown type करें</li><li>Right pane में rendered HTML live update होता है</li><li>Standard Markdown syntax उपयोग करें</li><li>Copy या download करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Live Preview</strong>: Type करते समय live HTML update होता है</li><li><strong>Side-by-Side View</strong>: Editor और preview एक साथ दिखाता है</li><li><strong>Full Markdown Support</strong>: Headers, bold, italic, lists, code blocks</li><li><strong>Syntax Highlighting</strong>: Code blocks में language-specific highlighting</li><li><strong>Copy HTML Output</strong>: Rendered HTML copy करें</li><li><strong>Responsive Layout</strong>: Desktop और mobile दोनों पर काम करता है</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>README Files</strong>: GitHub README files को preview करें</li><li><li>Blog Posts</strong>: Blog content को draft और preview करें</li><li><strong>Documentation</strong>: Technical documentation लिखें</li><li><strong>Note Taking</strong>: Quick formatted note-taking</li><li><strong>Email Drafts</strong>: Rich-text emails के लिए format करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Markdown Rendering", "content": "<p>Markdown <strong>ब्राउज़र में</strong> parse और render होता है।</p><ul><li>Content <strong>कभी server को नहीं जाता</strong></li><li>Confidential documentation के लिए safe</li><li>कोई cloud storage या sync नहीं</li><li>Offline काम करता है</li></ul>"}
    },
    "regex-tester": {
        "intro": {"title": "Regex Tester क्या है?", "content": "<p><strong>Regex Tester</strong> आपको regular expressions को test करने देता है।</p><p>Real-time matching के साथ patterns को debug करें।</p>"},
        "howToUse": {"title": "Regex Tester का उपयोग कैसे करें", "content": "<ol><li>Pattern field में regex pattern enter करें</li><li>Flags को set करें जैसे needed</li><li>Test text को type या paste करें</li><li>Matches real-time में highlight होते हैं</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Real-Time Matching</strong>: Matches instantly highlight होते हैं</li><li><strong>Flag Support</strong>: Global, case-insensitive, multiline flags</li><li><strong>Group Highlighting</strong>: Capture groups को distinct markers से दिखाता है</li><li><strong>Match Details</strong>: Full match text और groups दिखाता है</li><li><strong>Error Feedback</strong>: Invalid regex syntax को immediately report करता है</li><li><strong>Native Engine</strong>: Browser के built-in JavaScript regex engine का उपयोग</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>Pattern Development</strong>: Patterns को build और debug करें</li><li><strong>Data Validation</strong>: Email, phone number patterns test करें</li><li><strong>Text Parsing</strong>: Log files से data extract करने के लिए patterns develop करें</li><li><strong>Search & Replace</strong>: Replacement preview करें</li><li><strong>Learning</strong>: Interactive experimentation से regex सीखें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Regex Processing", "content": "<p>Pattern matching <strong>ब्राउज़र में</strong> native JavaScript RegExp engine से होता है।</p><ul><li>Patterns और test data <strong>कभी device को नहीं छोड़ते</strong></li><li>Sensitive data जैसे log files के साथ testing के लिए safe</li><li>Offline काम करता है</li></ul>"}
    },
    "timestamp": {
        "intro": {"title": "Unix Timestamp Converter क्या है?", "content": "<p><strong>Unix Timestamp Converter</strong> Unix timestamps और human-readable dates के बीच convert करता है।</p><p>Timestamp enter करें date देखने के लिए, या date pick करें timestamp प्राप्त करने के लिए।</p>"},
        "howToUse": {"title": "Unix Timestamp Converter का उपयोग कैसे करें", "content": "<ol><li>Unix timestamp enter करें human-readable date देखने के लिए</li><li>या date और time select करें corresponding timestamp प्राप्त करने के लिए</li><li>Current Unix timestamp live display होता है</li><li>One click से कोई भी value copy करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Bidirectional Conversion</strong>: Timestamp → date और date → timestamp</li><li><strong>Live Clock</strong>: Current Unix timestamp live display होता है</li><li><strong>Seconds & Milliseconds</strong>: Unix seconds और JavaScript milliseconds दोनों support करता है</li><li><strong>Local & UTC</strong>: Local timezone और UTC दोनों में times दिखाता है</li><li><strong>Instant Results</strong>: Real-time conversion</li><li><strong>One-Click Copy</strong>: Clipboard में copy करें</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>Debugging</strong>: API response timestamps को readable dates में convert करें</li><li><strong>Database Queries</strong>: SQL queries के लिए timestamp formats को convert करें</li><li><strong>Log Analysis</strong>: Log files में Unix timestamps को human-readable में translate करें</li><li><strong>Scheduling</strong>: Cron jobs के लिए future/past timestamps calculate करें</li><li><strong>Cross-Timezone Work</strong>: Timezones के बीच timestamps को compare करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Timestamp Processing", "content": "<p>सभी conversions <strong>ब्राउज़र-native Date API</strong> से होते हैं।</p><ul><li>Timestamps <strong>कभी device को नहीं छोड़ते</strong></li><li>Offline काम करता है</li></ul>"}
    },
    "yaml-json": {
        "intro": {"title": "YAML ↔ JSON Converter क्या है?", "content": "<p><strong>YAML ↔ JSON Converter</strong> YAML और JSON formats के बीच data को transform करता है।</p><p>Kubernetes configs, CI/CD pipelines, या कोई भी YAML file को JSON में convert करें।</p>"},
        "howToUse": {"title": "YAML ↔ JSON Converter का उपयोग कैसे करें", "content": "<ol><li>YAML या JSON data paste करें</li><li>Conversion direction चुनें</li><li>Output instantly दिखाई देता है</li><li>Copy या download करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Bidirectional Conversion</strong>: दोनों directions में convert करें</li><li><strong>Full YAML Support</strong>: Multi-line strings, anchors, aliases handle करता है</li><li><strong>Pretty-Printed Output</strong>: JSON और YAML output properly formatted है</li><li><strong>Error Reporting</strong>: Invalid YAML या JSON के लिए clear error messages</li><li><strong>Instant Processing</strong>: तुरंत results</li><li><strong>Powered by js-yaml</strong>: Industry-standard js-yaml library का उपयोग करता है</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>DevOps</strong>: Kubernetes, Docker Compose, Ansible YAML को JSON में convert करें</li><li><strong>CI/CD</strong>: GitHub Actions या GitLab CI YAML configs को JSON में transform करें</li><li><strong>Configuration</strong>: YAML और JSON configuration file formats के बीच convert करें</li><li><strong>API Development</strong>: YAML API specs (OpenAPI) को JSON में transform करें</li><li><strong>Data Migration</strong>: YAML और JSON के बीच data migrate करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Data Conversion", "content": "<p>Conversion <strong>ब्राउज़र में</strong> js-yaml library से होता है।</p><ul><li>Configuration files और data <strong>कभी device को नहीं छोड़ते</strong></li><li>Secrets, environment variables, sensitive configs के लिए safe</li><li>Offline काम करता है</li></ul>"}
    },
    "text-diff": {
        "intro": {"title": "Text Diff क्या है?", "content": "<p><strong>Text Diff</strong> दो texts को compare करता है और line-by-line differences को highlight करता है।</p><p>Exactly देखें कि क्या add, remove, या change हुआ।</p>"},
        "howToUse": {"title": "Text Diff का उपयोग कैसे करें", "content": "<ol><li>Left panel में original text paste करें</li><li>Right panel में modified text paste करें</li><li>Differences immediately highlight होते हैं</li><li>Diff को review करने के लिए scroll करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Line-by-Line Comparison</strong>: Exactly देखें कि कौन सी lines differ करती हैं</li><li><strong>Color-Coded Diff</strong>: Green for additions, red for deletions</li><li><strong>Instant Comparison</strong>: Text paste करते ही results दिखाई देते हैं</li><li><strong>Side-by-Side View</strong>: दोनों texts एक साथ aligned differences के साथ</li><li><strong>Large Text Support</strong>: Lengthy documents को efficiently compare करता है</li><li><strong>No Line Limit</strong>: कोई भी text length handle करता है</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>Code Review</strong>: Code versions को compare करें</li><li><strong>Config Changes</strong>: Development और production configs को compare करें</li><li><strong>Document Revision</strong>: Documents के draft versions को compare करें</li><li><strong>Database Records</strong>: Exported records को compare करें</li><li><strong>Debugging</strong>: Expected vs actual output को compare करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Text Comparison", "content": "<p>Comparison <strong>ब्राउज़र में</strong> JavaScript diff algorithm से होता है।</p><ul><li>Text <strong>कभी device को नहीं छोड़ता</strong></li><li>Sensitive code, contracts, confidential documents के लिए safe</li><li>कोई server storage या third-party access नहीं</li><li>Offline काम करता है</li></ul>"}
    },
    "word-counter": {
        "intro": {"title": "Word Counter क्या है?", "content": "<p><strong>Word Counter</strong> आपके text को analyze करता है और instantly word count, character count, sentence count, paragraph count, और estimated reading time display करता है।</p><p>Simply text paste करें और सभी statistics real-time में प्राप्त करें।</p>"},
        "howToUse": {"title": "Word Counter का उपयोग कैसे करें", "content": "<ol><li>Input area में text type या paste करें</li><li>Statistics real-time में update होते हैं जैसे आप type करते हैं</li><li>Length requirements check करने या reading duration estimate करने के लिए results का उपयोग करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Word Count</strong>: Accurate word counting</li><li><strong>Character Count</strong>: Total characters with और without spaces</li><li><strong>Sentence Count</strong>: Punctuation markers based पर count करता है</li><li><strong>Paragraph Count</strong>: Line breaks से separate paragraphs count करता है</li><li><strong>Reading Time</strong>: Average speed पर estimated reading duration</li><li><strong>Real-Time Updates</strong>: Type करते समय सभी statistics instantly update होते हैं</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>Academic Writing</strong>: Essay या thesis word counts को requirements से check करें</li><li><strong>SEO Content</strong>: Blog posts को target word counts से ensure करें</li><li><strong>Social Media</strong>: Tweets, LinkedIn posts के character limits check करें</li><li><strong>Translation</strong>: Word count से translation costs estimate करें</li><li><strong>Content Planning</strong>: Articles और presentations के लिए reading times calculate करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Text Analysis", "content": "<p>सभी counting <strong>ब्राउज़र में</strong> simple JavaScript string operations से होता है।</p><ul><li>Text <strong>कभी device को नहीं छोड़ता</strong></li><li>Confidential documents को analyze करने के लिए safe</li><li>कोई server processing या cloud storage नहीं</li><li>Offline काम करता है</li></ul>"}
    },
    "case-converter": {
        "intro": {"title": "Case Converter क्या है?", "content": "<p><strong>Case Converter</strong> text को multiple case formats के बीच transform करता है।</p><p>UPPERCASE, lowercase, Title Case, camelCase, snake_case, और अन्य formats के बीच convert करें।</p>"},
        "howToUse": {"title": "Case Converter का उपयोग कैसे करें", "content": "<ol><li>Input area में text type या paste करें</li><li>Desired case format button को click करें</li><li>Converted text instantly दिखाई देता है</li><li>One click से copy करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>9+ Case Formats</strong>: UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE</li><li><strong>Instant Conversion</strong>: Click करते ही results दिखाई देते हैं</li><li><strong>Multi-Line Support</strong>: एक साथ multiple lines convert करें</li><li><strong>Smart Parsing</strong>: camelCase या snake_case से words को correctly split करता है</li><li><strong>One-Click Copy</strong>: Clipboard में converted text copy करें</li><li><strong>Batch Processing</strong>: Multiple lines को simultaneously process करता है</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>Variable Naming</strong>: JavaScript camelCase, Python snake_case, CSS kebab-case के बीच convert करें</li><li><strong>Database Fields</strong>: Column names को different naming conventions में transform करें</li><li><strong>Content Formatting</strong>: Titles को Title Case में headlines के लिए convert करें</li><li><strong>API Design</strong>: JSON request/response schemas में field names को standardize करें</li><li><strong>Code Refactoring</strong>: Naming conventions के बीच switch करते समय identifiers को rename करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Text Processing", "content": "<p>Case conversion <strong>ब्राउज़र में</strong> JavaScript string operations से होता है।</p><ul><li>Text <strong>कभी device को नहीं छोड़ता</strong></li><li>कोई server processing या logging नहीं</li><li>Offline काम करता है</li></ul>"}
    },
    "lorem-ipsum": {
        "intro": {"title": "Lorem Ipsum Generator क्या है?", "content": "<p><strong>Lorem Ipsum Generator</strong> design mockups, wireframes, और prototypes के लिए placeholder text create करता है।</p><p>Exact amount control के साथ classic Lorem Ipsum text generate करें।</p>"},
        "howToUse": {"title": "Lorem Ipsum Generator का उपयोग कैसे करें", "content": "<ol><li>Unit choose करें: <strong>paragraphs</strong>, <strong>sentences</strong>, या <strong>words</strong></li><li>Amount set करें जो आपको चाहिए</li><li><strong>Generate</strong> को click करें placeholder text create करने के लिए</li><li>Design या document में use करने के लिए copy करें</li></ol>"},
        "features": {"title": "मुख्य विशेषताएं", "content": "<ul><li><strong>Three Output Modes</strong>: Paragraphs, sentences, या word count से generate करें</li><li><strong>Customizable Amount</strong>: Exactly कितना text generate होगा यह control करें</li><li><strong>Classic Lorem Ipsum</strong>: Standard Lorem Ipsum word pool का उपयोग करता है</li><li><strong>Instant Generation</strong>: Text immediately दिखाई देता है</li><li><strong>One-Click Copy</strong>: सभी generated text को clipboard में copy करें</li><li><strong>Consistent Output</strong>: Natural-looking text distribution</li></ul>"},
        "useCases": {"title": "सामान्य उपयोग के मामले", "content": "<ul><li><strong>Web Design</strong>: Page layouts को realistic text से fill करें</li><li><strong>UI Prototyping</strong>: Wireframes और mockups में placeholder content add करें</li><li><strong>Print Design</strong>: Brochures, flyers को final copy से पहले fill करें</li><li><li>Presentations</strong>: Slide templates में placeholder text add करें</li><li><strong>Testing</strong>: Text rendering या truncation test करने के लिए sample text generate करें</li></ul>"},
        "privacy": {"title": "गोपनीयता-प्रथम Text Generation", "content": "<p>Lorem Ipsum <strong>ब्राउज़र में</strong> local word dictionary से generate होता है।</p><ul><li>कोई data transmitted नहीं</li><li>Tool पूरी तरह generative है</li><li>Offline काम करता है</li></ul>"}
    }
}

# Portuguese-Brazil translations (similar structure)
PORTUGUESE_BR_TRANSLATIONS = {
    # ... (will contain Portuguese-Brazil translations)
}

print("Hindi translation dictionary loaded")
print(f"Tools with Hindi translations: {len(HINDI_TRANSLATIONS)}")
