import type { TextLayer } from "./reducer";

export interface StylePreset {
  id: string;
  name: string;
  preview: string;
  patch: Partial<TextLayer>;
}

/**
 * 15 hand-crafted style presets covering common text-on-image use cases.
 * Each preset replaces a subset of layer fields when applied.
 */
export const PRESETS: StylePreset[] = [
  {
    id: "clean-white",
    name: "Clean White",
    preview: "Aa",
    patch: {
      fontFamily: "Inter",
      fontWeight: 700,
      color: "#ffffff",
      strokeWidth: 0,
      shadowEnabled: false,
      bgMode: "none",
      opacity: 1,
    },
  },
  {
    id: "outlined-white",
    name: "Bold Outline",
    preview: "Aa",
    patch: {
      fontFamily: "Montserrat",
      fontWeight: 700,
      color: "#ffffff",
      strokeColor: "#000000",
      strokeWidth: 6,
      shadowEnabled: false,
      bgMode: "none",
      opacity: 1,
    },
  },
  {
    id: "soft-shadow",
    name: "Soft Shadow",
    preview: "Aa",
    patch: {
      fontFamily: "Inter",
      fontWeight: 600,
      color: "#ffffff",
      strokeWidth: 0,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 16,
      shadowOffsetX: 2,
      shadowOffsetY: 4,
      bgMode: "none",
      opacity: 1,
    },
  },
  {
    id: "meme",
    name: "Meme",
    preview: "AA",
    patch: {
      fontFamily: "Bebas Neue",
      fontWeight: 400,
      color: "#ffffff",
      strokeColor: "#000000",
      strokeWidth: 8,
      shadowEnabled: false,
      bgMode: "none",
      letterSpacing: 2,
      opacity: 1,
    },
  },
  {
    id: "headline",
    name: "Headline",
    preview: "Aa",
    patch: {
      fontFamily: "Playfair Display",
      fontWeight: 700,
      color: "#ffffff",
      strokeWidth: 0,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      bgMode: "none",
      opacity: 1,
    },
  },
  {
    id: "highlight-strip",
    name: "Highlight",
    preview: "Aa",
    patch: {
      fontFamily: "Inter",
      fontWeight: 700,
      color: "#000000",
      strokeWidth: 0,
      shadowEnabled: false,
      bgMode: "line",
      bgColor: "#FBBF24",
      bgOpacity: 1,
      bgPaddingX: 14,
      bgPaddingY: 6,
      bgRadius: 0,
    },
  },
  {
    id: "instagram-story",
    name: "Story",
    preview: "Aa",
    patch: {
      fontFamily: "Inter",
      fontWeight: 700,
      color: "#ffffff",
      strokeWidth: 0,
      shadowEnabled: false,
      bgMode: "full",
      bgColor: "#000000",
      bgOpacity: 0.7,
      bgPaddingX: 18,
      bgPaddingY: 10,
      bgRadius: 8,
    },
  },
  {
    id: "neon",
    name: "Neon Glow",
    preview: "Aa",
    patch: {
      fontFamily: "Bebas Neue",
      fontWeight: 400,
      color: "#ffffff",
      strokeWidth: 0,
      shadowEnabled: true,
      shadowColor: "#06B6D4",
      shadowBlur: 30,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      bgMode: "none",
      opacity: 1,
    },
  },
  {
    id: "retro-poster",
    name: "Retro Poster",
    preview: "Aa",
    patch: {
      fontFamily: "Playfair Display",
      fontWeight: 700,
      fontStyle: "italic",
      color: "#FCD34D",
      strokeColor: "#7C2D12",
      strokeWidth: 4,
      shadowEnabled: false,
      bgMode: "none",
    },
  },
  {
    id: "minimal-serif",
    name: "Minimal Serif",
    preview: "Aa",
    patch: {
      fontFamily: "Merriweather",
      fontWeight: 400,
      color: "#ffffff",
      strokeWidth: 0,
      shadowEnabled: false,
      bgMode: "none",
      letterSpacing: 1,
      opacity: 0.95,
    },
  },
  {
    id: "handwritten",
    name: "Handwritten",
    preview: "Aa",
    patch: {
      fontFamily: "Pacifico",
      fontWeight: 400,
      color: "#ffffff",
      strokeWidth: 0,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 8,
      shadowOffsetX: 1,
      shadowOffsetY: 2,
      bgMode: "none",
      rotationDeg: -4,
    },
  },
  {
    id: "vintage-sign",
    name: "Vintage Sign",
    preview: "Aa",
    patch: {
      fontFamily: "Lobster",
      fontWeight: 400,
      color: "#FBBF24",
      strokeColor: "#1F2937",
      strokeWidth: 3,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 10,
      shadowOffsetX: 3,
      shadowOffsetY: 3,
      bgMode: "none",
    },
  },
  {
    id: "marker",
    name: "Marker",
    preview: "Aa",
    patch: {
      fontFamily: "Permanent Marker",
      fontWeight: 400,
      color: "#EF4444",
      strokeWidth: 0,
      shadowEnabled: false,
      bgMode: "none",
      rotationDeg: -3,
    },
  },
  {
    id: "subtitle",
    name: "Subtitle",
    preview: "Aa",
    patch: {
      fontFamily: "Inter",
      fontWeight: 600,
      color: "#ffffff",
      strokeColor: "#000000",
      strokeWidth: 4,
      shadowEnabled: true,
      shadowColor: "#000000",
      shadowBlur: 6,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      bgMode: "none",
    },
  },
  {
    id: "watermark-soft",
    name: "Soft Mark",
    preview: "Aa",
    patch: {
      fontFamily: "Montserrat",
      fontWeight: 600,
      color: "#ffffff",
      strokeWidth: 0,
      shadowEnabled: false,
      bgMode: "none",
      opacity: 0.45,
      letterSpacing: 4,
    },
  },
];
